apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: |
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: nexops-app
    spec:
      rules:
      - host: staging.nexops.local
        http:
          paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nexops-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexops-frontend
                port:
                  number: 80
      tls:
      - hosts:
        - staging.nexops.local
        secretName: nexops-app-tls
